version: '2.2'

services:
  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile
      args:
        API_URI: 'http://3.16.58.159/graphql/'
    environment:
      - API_URI=http://3.16.58.159/graphql/
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    networks:
      - saleor-backend-tier

  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile
    environment:
      - API_URI=http://3.16.58.159/graphql/
    expose:
      - 9000
    restart: unless-stopped
    volumes:
      - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    networks:
      - saleor-backend-tier

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - static_volume:/home/app/static/
      - saleor-media:/app/media
    ports:
      - 80:80
    links:
      - dashboard:dashboard
      - storefront:storefront
    depends_on:
      - dashboard
      - storefront
    networks:
      - saleor-backend-tier

volumes:
  saleor-media:
  static_volume:

networks:
  saleor-backend-tier:
    driver: bridge
